# Generated by Django 4.1.7 on 2023-06-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carbrand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carbrand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carmodel'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.enginetype'),
        ),
    ]
